 [package]
 name = "footballcaster2"
 version = "0.1.0"
 edition = "2021"

 [lib]
 crate-type = ["cdylib"]

 [dependencies]
 spacetimedb = "=1.9.0"
 serde = { version = "1", features = ["derive"] }
 serde_json = "1"
 log = "0.4"
 humantime = "2"
 uuid = { version = "1", features = ["v5"] }